### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Domosed-gamin** [Entalpi/ColoniaC#1]
Game don't work. 

> ```
> ```
> [1] EFFECTS [+]
> Colonia organisation: Established colonia.
> 
> [2] CONSTRUCTIONS [+]
> 
> [3] RESOURCES [+]
> Gold (0.00): 100.00 kg
> Food consumption: 0.0 kcal
> IMPORTING FOOD
> Land area: 100
> 
> Political  power: 0 / 0
> Military   power: 0 / 0
> Diplomatic power: 0 / 0
> 
> [4] DEMOGRAPHICS [+]
> Population: 300
> Births: 0.0 / day
> Deaths: 0.0 / day
> Immigrations: 0.0 / day
> Emmigrations: 0.0 / day
> 
> 
> 
> 
> Speed: 1 / 9 | Q: menu | C: construction | P: policy | H: helpОшибка сегментирования
> ```
> 
> ```

Words "Ошибка сегментирования" is segmentation fault in Russian.

**Comment by lingtorp** [comment]
Yeah, this game is very much in development. This is one of the known bugs. I will get back when it is fixed. :)
